# .streamlit/secrets.toml

[telegram]
# O Token é o código longo que o BotFather te deu
bot_token = "8109891755:AAEJ5bzbXxb9QRd06PaME9V4qB4XDC_G2I0"

# O Chat ID é o número (geralmente curto)
chat_id = "1226530934"